### ISSUE TITLE
Issues with clustered redis

### ISSUE THREAD

**Issue by andianderson522** [hapijs/catbox-redis#54] opened 2016-11-16 15:41 UTC
When using a clustered redis we get the following errors intermittently:

`id=1479306778963:IST:10139:ivl121e5:10027, url=/, method=GET, env=local, userAgent=node-superagent/1.8.4, requestIp=127.0.0.1, referrer=, xClient=integration, xForwardedFor=undefined, endpoint=api, message=MOVED 11927 10.91.54.52:6379, stack=ReplyError: MOVED 11927 10.91.54.52:6379
    at parseError (/Users/aanders3/Documents/projects/user-platform-infinityid/node_modules/redis/node_modules/redis-parser/lib/parser.js:167:12)
    at parseType (/Users/aanders3/Documents/projects/user-platform-infinityid/node_modules/redis/node_modules/redis-parser/lib/parser.js:228:14), type=error`

our cache config is as follows:
`cache: [{
      engine: require('catbox-redis'),
      host: config.redis.host,
      port: config.redis.port,
      partition: config.cachePartition,
      shared: true
    }]`

Please let me know how I can fix this.

**Comment by Marsup** [comment] 2016-11-16 16:13
Feels like a question you should direct at the redis module, not catbox.

**Comment by LoicMahieu** [comment] 2017-03-28 15:36
catbox-redis@3.0.1 is out. We switch to `ioredis` for communication with Redis.
So I close the issue but feel free to open a new one if you think the problem is not solved.
Thanks.

**Closed by LoicMahieu** 2017-03-28 15:36 UTC

**Comment by curious12coder1** [comment] 2018-07-07 06:29
How do we specify the cluster redis info? say I have 3 redis nodes in the cluster, how to specify them in the config cache?

**Comment by marcuspoehls** [comment] 2018-07-10 07:52
@curious12coder1 You need to pass a custom `client` to `catbox-redis`
